### PR TITLE
Symfony 6

### PR DESCRIPTION
**Pull request by flavou45**
- Add support for Symfony 6
- Add support for PHP 8 attributes and types
- Fix one deprecation and one bug

### CODE REVIEW

**Comment by EmilePerron** [comment]
I'm facing a few issues with this PR when trying to use it locally.

When cloning the repo locally and running tests, there are lots of `Typed property X must not be accessed before initialization` errors:

```
PHPUnit 9.5.11 by Sebastian Bergmann and contributors.

..SEEEES.....E.......EEEEEE                                       27 / 27 (100%)

Time: 00:00.053, Memory: 14.00 MB

There were 11 errors:

1) Ambta\DoctrineEncryptBundle\Tests\Unit\Encryptors\DefuseEncryptorTest::testEncrypt
Error: Typed property Ambta\DoctrineEncryptBundle\Encryptors\DefuseEncryptor::$encryptionKey must not be accessed before initialization

/Users/emileperron/Open-source Workspace/DoctrineEncryptBundle/src/Encryptors/DefuseEncryptor.php:46
/Users/emileperron/Open-source Workspace/DoctrineEncryptBundle/src/Encryptors/DefuseEncryptor.php:33
/Users/emileperron/Open-source Workspace/DoctrineEncryptBundle/Tests/Unit/Encryptors/DefuseEncryptorTest.php:18

2) Ambta\DoctrineEncryptBundle\Tests\Unit\Encryptors\DefuseEncryptorTest::testGenerateKey
Error: Typed property Ambta\DoctrineEncryptBundle\Encryptors\DefuseEncryptor::$encryptionKey must not be accessed before initialization

/Users/emileperron/Open-source Workspace/DoctrineEncryptBundle/src/Encryptors/DefuseEncryptor.php:46
/Users/emileperron/Open-source Workspace/DoctrineEncryptBundle/src/Encryptors/DefuseEncryptor.php:33
/Users/emileperron/Open-source Workspace/DoctrineEncryptBundle/Tests/Unit/Encryptors/DefuseEncryptorTest.php:34

3) Ambta\DoctrineEncryptBundle\Tests\Unit\Encryptors\HaliteEncryptorTest::testEncryptExtension
Error: Typed property Ambta\DoctrineEncryptBundle\Encryptors\HaliteEncryptor::$encryptionKey must not be accessed before initialization

/Users/emileperron/Open-source Workspace/DoctrineEncryptBundle/src/Encryptors/HaliteEncryptor.php:55
/Users/emileperron/Open-source Workspace/DoctrineEncryptBundle/src/Encryptors/HaliteEncryptor.php:35
/Users/emileperron/Open-source Workspace/DoctrineEncryptBundle/Tests/Unit/Encryptors/HaliteEncryptorTest.php:21

4) Ambta\DoctrineEncryptBundle\Tests\Unit\Encryptors\HaliteEncryptorTest::testGenerateKey
Error: Typed property Ambta\DoctrineEncryptBundle\Encryptors\HaliteEncryptor::$encryptionKey must not be accessed before initialization

/Users/emileperron/Open-source Workspace/DoctrineEncryptBundle/src/Encryptors/HaliteEncryptor.php:55
/Users/emileperron/Open-source Workspace/DoctrineEncryptBundle/src/Encryptors/HaliteEncryptor.php:35
/Users/emileperron/Open-source Workspace/DoctrineEncryptBundle/Tests/Unit/Encryptors/HaliteEncryptorTest.php:40

5) Ambta\DoctrineEncryptBundle\Tests\Unit\Subscribers\DoctrineEncryptSubscriberTest::testProcessFieldsNoEncryptor
TypeError: Cannot assign null to property Ambta\DoctrineEncryptBundle\Subscribers\DoctrineEncryptSubscriber::$encryptor of type Ambta\DoctrineEncryptBundle\Encryptors\EncryptorInterface

/Users/emileperron/Open-source Workspace/DoctrineEncryptBundle/src/Subscribers/DoctrineEncryptSubscriber.php:92
/Users/emileperron/Open-source Workspace/DoctrineEncryptBundle/Tests/Unit/Subscribers/DoctrineEncryptSubscriberTest.php:132

6) Ambta\DoctrineEncryptBundle\Tests\Functional\BasicQueryTest\BasicQueryDefuseTest::testPersistEntity
Error: Typed property Ambta\DoctrineEncryptBundle\Encryptors\DefuseEncryptor::$encryptionKey must not be accessed before initialization

/Users/emileperron/Open-source Workspace/DoctrineEncryptBundle/src/Encryptors/DefuseEncryptor.php:46
/Users/emileperron/Open-source Workspace/DoctrineEncryptBundle/src/Encryptors/DefuseEncryptor.php:33
/Users/emileperron/Open-source Workspace/DoctrineEncryptBundle/src/Subscribers/DoctrineEncryptSubscriber.php:272
/Users/emileperron/Open-source Workspace/DoctrineEncryptBundle/src/Subscribers/DoctrineEncryptSubscriber.php:182
/Users/emileperron/Open-source Workspace/DoctrineEncryptBundle/vendor/doctrine/event-manager/lib/Doctrine/Common/EventManager.php:41
/Users/emileperron/Open-source Workspace/DoctrineEncryptBundle/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:3472
/Users/emileperron/Open-source Workspace/DoctrineEncryptBundle/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:398
/Users/emileperron/Open-source Workspace/DoctrineEncryptBundle/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php:392
/Users/emileperron/Open-source Workspace/DoctrineEncryptBundle/Tests/Functional/BasicQueryTest/AbstractBasicQueryTestCase.php:17

7) Ambta\DoctrineEncryptBundle\Tests\Functional\BasicQueryTest\BasicQueryDefuseTest::testNoUpdateOnReadEncrypted
Error: Typed property Ambta\DoctrineEncryptBundle\Encryptors\DefuseEncryptor::$encryptionKey must not be accessed before initialization

/Users/emileperron/Open-source Workspace/DoctrineEncryptBundle/src/Encryptors/DefuseEncryptor.php:46
/Users/emileperron/Open-source Workspace/DoctrineEncryptBundle/src/Encryptors/DefuseEncryptor.php:33
/Users/emileperron/Open-source Workspace/DoctrineEncryptBundle/src/Subscribers/DoctrineEncryptSubscriber.php:272
/Users/emileperron/Open-source Workspace/DoctrineEncryptBundle/src/Subscribers/DoctrineEncryptSubscriber.php:182
/Users/emileperron/Open-source Workspace/DoctrineEncryptBundle/vendor/doctrine/event-manager/lib/Doctrine/Common/EventManager.php:41
/Users/emileperron/Open-source Workspace/DoctrineEncryptBundle/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:3472
/Users/emileperron/Open-source Workspace/DoctrineEncryptBundle/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:398
/Users/emileperron/Open-source Workspace/DoctrineEncryptBundle/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php:392
/Users/emileperron/Open-source Workspace/DoctrineEncryptBundle/Tests/Functional/BasicQueryTest/AbstractBasicQueryTestCase.php:33

8) Ambta\DoctrineEncryptBundle\Tests\Functional\BasicQueryTest\BasicQueryDefuseTest::testStoredDataIsEncrypted
Error: Typed property Ambta\DoctrineEncryptBundle\Encryptors\DefuseEncryptor::$encryptionKey must not be accessed before initialization

/Users/emileperron/Open-source Workspace/DoctrineEncryptBundle/src/Encryptors/DefuseEncryptor.php:46
/Users/emileperron/Open-source Workspace/DoctrineEncryptBundle/src/Encryptors/DefuseEncryptor.php:33
/Users/emileperron/Open-source Workspace/DoctrineEncryptBundle/src/Subscribers/DoctrineEncryptSubscriber.php:272
/Users/emileperron/Open-source Workspace/DoctrineEncryptBundle/src/Subscribers/DoctrineEncryptSubscriber.php:182
/Users/emileperron/Open-source Workspace/DoctrineEncryptBundle/vendor/doctrine/event-manager/lib/Doctrine/Common/EventManager.php:41
/Users/emileperron/Open-source Workspace/DoctrineEncryptBundle/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:3472
/Users/emileperron/Open-source Workspace/DoctrineEncryptBundle/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:398
/Users/emileperron/Open-source Workspace/DoctrineEncryptBundle/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php:392
/Users/emileperron/Open-source Workspace/DoctrineEncryptBundle/Tests/Functional/BasicQueryTest/AbstractBasicQueryTestCase.php:66

9) Ambta\DoctrineEncryptBundle\Tests\Functional\BasicQueryTest\BasicQueryHaliteTest::testPersistEntity
Error: Typed property Ambta\DoctrineEncryptBundle\Encryptors\HaliteEncryptor::$encryptionKey must not be accessed before initialization

/Users/emileperron/Open-source Workspace/DoctrineEncryptBundle/src/Encryptors/HaliteEncryptor.php:55
/Users/emileperron/Open-source Workspace/DoctrineEncryptBundle/src/Encryptors/HaliteEncryptor.php:35
/Users/emileperron/Open-source Workspace/DoctrineEncryptBundle/src/Subscribers/DoctrineEncryptSubscriber.php:272
/Users/emileperron/Open-source Workspace/DoctrineEncryptBundle/src/Subscribers/DoctrineEncryptSubscriber.php:182
/Users/emileperron/Open-source Workspace/DoctrineEncryptBundle/vendor/doctrine/event-manager/lib/Doctrine/Common/EventManager.php:41
/Users/emileperron/Open-source Workspace/DoctrineEncryptBundle/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:3472
/Users/emileperron/Open-source Workspace/DoctrineEncryptBundle/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:398
/Users/emileperron/Open-source Workspace/DoctrineEncryptBundle/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php:392
/Users/emileperron/Open-source Workspace/DoctrineEncryptBundle/Tests/Functional/BasicQueryTest/AbstractBasicQueryTestCase.php:17

10) Ambta\DoctrineEncryptBundle\Tests\Functional\BasicQueryTest\BasicQueryHaliteTest::testNoUpdateOnReadEncrypted
Error: Typed property Ambta\DoctrineEncryptBundle\Encryptors\HaliteEncryptor::$encryptionKey must not be accessed before initialization

/Users/emileperron/Open-source Workspace/DoctrineEncryptBundle/src/Encryptors/HaliteEncryptor.php:55
/Users/emileperron/Open-source Workspace/DoctrineEncryptBundle/src/Encryptors/HaliteEncryptor.php:35
/Users/emileperron/Open-source Workspace/DoctrineEncryptBundle/src/Subscribers/DoctrineEncryptSubscriber.php:272
/Users/emileperron/Open-source Workspace/DoctrineEncryptBundle/src/Subscribers/DoctrineEncryptSubscriber.php:182
/Users/emileperron/Open-source Workspace/DoctrineEncryptBundle/vendor/doctrine/event-manager/lib/Doctrine/Common/EventManager.php:41
/Users/emileperron/Open-source Workspace/DoctrineEncryptBundle/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:3472
/Users/emileperron/Open-source Workspace/DoctrineEncryptBundle/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:398
/Users/emileperron/Open-source Workspace/DoctrineEncryptBundle/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php:392
/Users/emileperron/Open-source Workspace/DoctrineEncryptBundle/Tests/Functional/BasicQueryTest/AbstractBasicQueryTestCase.php:33

11) Ambta\DoctrineEncryptBundle\Tests\Functional\BasicQueryTest\BasicQueryHaliteTest::testStoredDataIsEncrypted
Error: Typed property Ambta\DoctrineEncryptBundle\Encryptors\HaliteEncryptor::$encryptionKey must not be accessed before initialization

/Users/emileperron/Open-source Workspace/DoctrineEncryptBundle/src/Encryptors/HaliteEncryptor.php:55
/Users/emileperron/Open-source Workspace/DoctrineEncryptBundle/src/Encryptors/HaliteEncryptor.php:35
/Users/emileperron/Open-source Workspace/DoctrineEncryptBundle/src/Subscribers/DoctrineEncryptSubscriber.php:272
/Users/emileperron/Open-source Workspace/DoctrineEncryptBundle/src/Subscribers/DoctrineEncryptSubscriber.php:182
/Users/emileperron/Open-source Workspace/DoctrineEncryptBundle/vendor/doctrine/event-manager/lib/Doctrine/Common/EventManager.php:41
/Users/emileperron/Open-source Workspace/DoctrineEncryptBundle/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:3472
/Users/emileperron/Open-source Workspace/DoctrineEncryptBundle/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:398
/Users/emileperron/Open-source Workspace/DoctrineEncryptBundle/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php:392
/Users/emileperron/Open-source Workspace/DoctrineEncryptBundle/Tests/Functional/BasicQueryTest/AbstractBasicQueryTestCase.php:66

ERRORS!
Tests: 27, Assertions: 37, Errors: 11, Skipped: 2.
```

I think this could be fixed by replacing the `$this->var === null` checks by `!isset($this->var)`. 

I'm also facing a `Cannot use object of type App\Entity\SomeClass as array` error when attempting to use the PR's version in a local project. This issue takes place here:
https://github.com/flavou45/DoctrineEncryptBundle/blob/03896aa9e45f4ce9295dfe650223e9e2a55afc55/src/Command/DoctrineEncryptDatabaseCommand.php#L87

It seems like `$row` in this instance is an instance of my entity, but clearly the code believes it to be an array of some sort.
Changing `$row[0]` to `$row` seems to fix it, but I'm unsure of the actual cause of the issue here.

**Review by flavou45 — COMMENTED** [review]
Errors have been corrected.
All unit tests are ok.

**Comment by EmilePerron** [comment]
Thanks for the quick fix! 
Tests run fine with no errors now, and it works correctly on my local project as well.

This PR has my thumbs up! 👍

**Comment by atrigub** [comment]
Hi guys, do you have plans for merge it?

**Comment by virtualize** [comment]
LGTM @absolute-quantum what is needed to have this one merged and have a new release?

**Comment by virtualize** [comment]
Thanks a lot!

**Pull request merged**
