### PR TITLE
Upgrade PHPUnit to 8+ and allow the package to be installed with PHP 8.0

### PR DESCRIPTION
**Pull request by sebb**

### CODE REVIEW

**Comment by v-matsuk** [comment]
Really looking forward for this PR to be merged. Seems like it's the only blocker for switch to php 8.

**Comment by Moskydesign** [comment]
Also hope this can be merged soon. Let me know if I can help.

**Comment by v-matsuk** [comment]
Guys, any news on that?

**Comment by cs-akash-jarad** [comment]
@GiveMeAllYourCats any update on this ? is this repo not maintained anymore ?

**Comment by loic425** [comment]
This one seems to be maintained https://github.com/MikeDevresse/DoctrineEncryptBundle

**Comment by angelomelonas** [comment]
Would be amazing to have this merged.

**Comment by absolute-quantum** [comment]
UPDATED @ 5.0.0

**Pull request merged**
